name: Lint, test and build
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: lint
        run: npm run lint
      - name: test
        run: npm test
      - name: build
        run: npm run build